[package]

name = "queryst"
version = "0.1.1"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]
description = "Rust query string parser with nesting support"
repository = "https://github.com/rustless/queryst"
keywords = ["json", "web", "url", "parser"]
license = "MIT"

[dependencies]
url = "~0.2.0"
